

# af table (genomes downloaded from RefSeq)
input_table_af: af_table.tsv
# table with local genomes. 2 columns: 1) genome label 2) path to fna file
input_table_local: local_table.tsv

########### assembly finder config

# download 2 genomes per species of the target taxid (e.g Staphylococcus genus)
Rank_to_filter_by: species
n_by_rank: 2
NCBI_key: '6dce38824889f62e188a25ae35c52a083c08'
NCBI_email: 'valentin.scherz@chuv.ch'
##Parameters for search_assemblies function
#This set of parameters is to search all possible assemblies
complete_assemblies: False
reference_assemblies: False
representative_assemblies: False
exclude_from_metagenomes: True
Genbank_assemblies: False
Refseq_assemblies: True
##Parameters for the filtering function

#None: Assemblies are ranked by their assembly status (complete or not)
#and Refseq category (reference, representative ...)
#If you want to filter by species, set this parameter to 'species'. The filtering function will list all unique species
#and rank their assemblies according to assembly status and Refseq category.
